local store = require("fsm.store")
local config = require("fsm.config")
local utils = require("fsm.utils")

describe("store", function()
  local test_dir

  before_each(function()
    -- Use a fresh temp directory for each test
    test_dir = vim.fn.tempname()
    config.setup({ data_dir = test_dir })
  end)

  after_each(function()
    -- Cleanup
    vim.fn.delete(test_dir, "rf")
  end)

  describe("create", function()
    it("creates a new focus", function()
      local focus, err = store.create("Test Focus")
      assert.is_nil(err)
      assert.is_not_nil(focus)
      assert.equals("test-focus", focus.slug)
      assert.equals("Test Focus", focus.name)
      assert.equals("active", focus.state)
    end)

    it("rejects duplicate names", function()
      store.create("Test Focus")
      local focus, err = store.create("Test Focus")
      assert.is_nil(focus)
      assert.truthy(err:match("already exists"))
    end)

    it("creates focus files", function()
      local focus = store.create("Test Focus")
      assert.is_true(utils.path_exists(store.notes_path(focus.slug)))
      assert.is_true(utils.path_exists(store.todo_path(focus.slug)))
    end)

    it("sets workspace number if provided", function()
      local focus = store.create("Test Focus", 10)
      assert.equals(10, focus.workspace_num)
      assert.equals("10:FOCUS-test-focus", focus.workspace_name)
    end)
  end)

  describe("load", function()
    it("loads existing focus", function()
      store.create("Test Focus")
      local focus, err = store.load("test-focus")
      assert.is_nil(err)
      assert.equals("test-focus", focus.slug)
    end)

    it("returns error for non-existent focus", function()
      local focus, err = store.load("non-existent")
      assert.is_nil(focus)
      assert.is_not_nil(err)
    end)
  end)

  describe("save", function()
    it("updates existing focus", function()
      local focus = store.create("Test Focus")
      focus.state = "suspended"
      local ok, err = store.save(focus)
      assert.is_true(ok)
      assert.is_nil(err)

      local loaded = store.load("test-focus")
      assert.equals("suspended", loaded.state)
    end)
  end)

  describe("exists", function()
    it("returns true for existing focus", function()
      store.create("Test Focus")
      assert.is_true(store.exists("test-focus"))
    end)

    it("returns false for non-existent focus", function()
      assert.is_false(store.exists("non-existent"))
    end)
  end)

  describe("list", function()
    it("lists all focus slugs", function()
      store.create("Focus One")
      store.create("Focus Two")
      local slugs = store.list()
      assert.equals(2, #slugs)
    end)

    it("returns empty list when no focuses", function()
      local slugs = store.list()
      assert.equals(0, #slugs)
    end)
  end)

  describe("list_all", function()
    it("returns full metadata for all focuses", function()
      store.create("Focus One")
      store.create("Focus Two")
      local focuses = store.list_all()
      assert.equals(2, #focuses)
      assert.truthy(focuses[1].name)
      assert.truthy(focuses[1].state)
    end)
  end)

  describe("archive", function()
    it("archives a focus", function()
      store.create("Test Focus", 10)
      local ok, err = store.archive("test-focus")
      assert.is_true(ok)
      assert.is_nil(err)

      local focus = store.load("test-focus")
      assert.equals("archived", focus.state)
      assert.is_nil(focus.workspace_num)
      assert.is_nil(focus.workspace_name)
    end)
  end)

  describe("delete", function()
    it("deletes a focus", function()
      store.create("Test Focus")
      local ok, err = store.delete("test-focus")
      assert.is_true(ok)
      assert.is_nil(err)
      assert.is_false(store.exists("test-focus"))
    end)

    it("returns error for non-existent focus", function()
      local ok, err = store.delete("non-existent")
      assert.is_false(ok)
      assert.is_not_nil(err)
    end)
  end)

  describe("by_state", function()
    it("filters by state", function()
      local f1 = store.create("Focus One")
      store.create("Focus Two")
      f1.state = "suspended"
      store.save(f1)

      local suspended = store.by_state("suspended")
      assert.equals(1, #suspended)
      assert.equals("focus-one", suspended[1].slug)

      local active = store.by_state("active")
      assert.equals(1, #active)
      assert.equals("focus-two", active[1].slug)
    end)
  end)

  describe("urls", function()
    it("saves and loads urls", function()
      store.create("Test Focus")
      local urls = { "https://example.com", "https://test.com" }
      store.save_urls("test-focus", urls)

      local loaded = store.load_urls("test-focus")
      assert.equals(2, #loaded)
      assert.equals("https://example.com", loaded[1])
      assert.equals("https://test.com", loaded[2])
    end)

    it("returns empty list when no urls", function()
      store.create("Test Focus")
      local loaded = store.load_urls("test-focus")
      assert.equals(0, #loaded)
    end)
  end)
end)
